# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown_file', models.CharField(max_length=128, verbose_name='md filename')),
            ],
        ),
    ]
