#!/usr/bin/env python3

import shutil
import glob
import sys
import os


def merge_dicts(*dict_args):
    """
    Given any number of dicts, shallow copy and merge into a new dictionary
    """
    result = {}
    for dictionary in dict_args:
        result.update(dictionary)
    return result


def import_node_status():
    """
    import files generated by Nepi routine
    """

    source_dir  = '/Users/nano/Documents/Inria/nepi/nepi_helper/'
    dest_dir    = 'markdown/'
    
    for filename in glob.glob(os.path.join(source_dir, '*.json')):
        shutil.copy(filename, dest_dir)


def main():
    import_node_status()

    
if __name__ == '__main__':
    main()