#!/usr/bin/env python3

import shutil
import glob
import sys
import os
import json
import datetime

def merge_dicts(*dict_args):
    """
    Given any number of dicts, shallow copy and merge into a new dictionary
    """
    result = {}
    for dictionary in dict_args:
        result.update(dictionary)
    return result


def modification_date(filename):
    """
    Return file modification datetime
    """
    t = os.path.getmtime(filename)
    return datetime.datetime.fromtimestamp(t)


def import_node_status():
    """
    Import files generated by Nepi routine
    """

    source_dir = os.getcwd() + "/results_nepi_helper/"
    dest_dir   = os.getcwd() + '/markdown/'
    
    results = {}

    for filename in glob.glob(os.path.join(source_dir, '*.json')):
        shutil.copy(filename, dest_dir)
     
        filename_base = os.path.basename(filename).replace('.json', '')
        results.update({ filename_base : {'last_modified': str(modification_date(filename))} })

    file = open(dest_dir+'info_files.json', "w")
    file.write('info_files' + " = '" + json.dumps(results) + "'")
    file.close()


def main():
    import_node_status()

    
if __name__ == '__main__':
    main()