#!/usr/bin/env python3

import shutil
import glob
import sys
import os
import json
import datetime

def merge_dicts(*dict_args):
    """
    Given any number of dicts, shallow copy and merge into a new dictionary
    """
    result = {}
    for dictionary in dict_args:
        result.update(dictionary)
    return result


def modification_date(filename):
    """
    Return file modification datetime
    """
    t = os.path.getmtime(filename)
    date_time_file = datetime.datetime.fromtimestamp(t)
    return date_time_file.strftime('%Y-%m-%d %H:%M')


def import_node_status():
    """
    Import files generated by Nepi routine
    """

    source_dir = os.getcwd() + "/results_nepi_helper/"
    dest_dir   = os.getcwd() + '/markdown/'
    
    results = {}

    for filename in glob.glob(os.path.join(source_dir, '*.json')):
        shutil.copy(filename, dest_dir)
     
        filename_base = os.path.basename(filename).replace('.json', '')
        results.update({ filename_base : {'last_modified': str(modification_date(filename))} })

    file = open(dest_dir+'info_files.json', "w")
    file.write('info_files' + " = '" + json.dumps(results) + "'")
    file.close()


def translate_single_json_file():
    """
    Join all the results in one json file
    """
    source_dir = os.getcwd() + "/results_nepi/"
    dest_dir   = os.getcwd() + '/markdown/'
    
    results = {}

    for node in range(1,38):
        results.update({node : {"cmi_card":"","ping":"","on_off":"","so_release":""}})
    
    temp = {}
    for file in glob.glob(os.path.join(source_dir, '*.json')):    
        with open(file) as data_file:
            data = json.load(data_file)
            file_name = os.path.basename(file)
            
            
            if "multiple_results.json" in file_name:
                element_from = "status"
                element_to   = "on_off"
            elif "alive_results.json" in file_name:
                element_from = "alive"
                element_to   = "cmi_card"
            elif "answer_results.json" in file_name:
                element_from = "answer"
                element_to   = "ping"
            elif "info_results.json" in file_name:
                element_from = "info"
                element_to   = "so_release"

            for k,v in data.items():
                value = v[element_from]
                if value == "alive" or value == "load" or value == "answer" or value == "reset":
                    value = "ok"

                key   = int(k)
                results[key][element_to] = value

    with open(dest_dir+'all_resuls_from_nepi.json', 'w') as outfile:
        json.dump(results, outfile)


def main():
    import_node_status()
    translate_single_json_file()

    
if __name__ == '__main__':
    main()